### ISSUE TITLE
Possible Committee Members

### ISSUE THREAD

**Issue by hmarschall** [AndreWeiner/mlfoam#2]
Hi all,

I just wanted to open another item to collect up-to-date work related to data-driven modeling in OpenFOAM - in the hope to identify researchers as candidates to approach for becoming active members of this committee.

To start with, allow me to point to this work: https://www.researchgate.net/publication/356496618_Acceleration_of_Chemical_Kinetics_Computation_with_the_Learned_Intelligent_Tabulation_LIT_Method

Best regards,
Holger

**Comment by AndreWeiner** [comment]
Hi Holger,
the idea to collect work around data-driven modeling and OpenFOAM is excellent. I created a list in the README file with 3 major categories - research items, software projects, and educational material. I also wrote up some requirements (draft). I did a small google search on the projected you linked and it seems that the authors' work is not available. This raises the question of how much use the item would be for the community. Maybe we could split the list in something like *papers with code* and *papers without code*. What do you think?
Best, Andre

**Comment by hmarschall** [comment]
Hi Andre,
this makes sense to me. Maybe it's a good idea to distinguish code from literature, where implementations are described. We should collect both - a list of repos and a list of papers / reports. What do you think?
Best regards,
Holger

**Comment by AndreWeiner** [comment]
Sure, let's split the list into research articles and research+code.

**Comment by tmaric** [comment]
:+1:
