### ISSUE TITLE
Contribution guidelines

### ISSUE THREAD

**Issue by AndreWeiner** [AndreWeiner/mlfoam#4]
Hi @tmaric and @hmarschall,
I created an initial version of [contribution](https://github.com/AndreWeiner/mlfoam/blob/main/CONTRIBUTING.md) guidelines. The document is really only an initial effort and by no means set in stone. Let's discuss the guidelines here.
Best, Andre

**Comment by tmaric** [comment]
I've edited the text a bit, here are a few comments: 

1. Lines of code is not a good measure of acceptance. Give me a surface tension approximator with 10 lines of code for VOF and I will dance in the street. 
2. ~~The contributors are told to provide a link to the code, the question is where? Do we create another .md file with the list of all data-driven OpenFOAM projects?~~ Missed this, I'll update the contribution guidelines.

**Comment by AndreWeiner** [comment]
Sure, the lines of code I suggested were only a rough estimate. With the ~1000 lines, I wanted to refer only to pure software projects (libraries or standalone applications) and not necessarily research projects, and I would consider really every line of source code (documentation, scripts for automation, scripts for post-processing, ...). If a research project requires changing only a single line of code to get improved results, that's of course perfectly fine. The only motivation for introducing the limit was to avoid bloating the link list with fragmented code snippets - because it would be really hard to keep track and check, e.g., for redundancy, and the list would become less useful.

Maybe we could clarity the text in the guidelines. Do you have a better measure in mind, or do you think the threshold is not really useful after all?

Cheers, Andre

**Comment by tmaric** [comment]
Not sure how to define it alternatively, and the motivation makes perfect sense. Maybe we can just state what you wrote in the answer: the goal is to link full-fledged software projects that address a specific topic and not code-snippets?

**Comment by AndreWeiner** [comment]
I just read through the contribution guidelines again. I think the requirements make it already quite clear that we are not looking for code snippets, so I think no changes are required :+1: 
Best, Andre

**Comment by tmaric** [comment]
:+1:
